<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>HeroDangle</AssemblyName>
    <RootNamespace>HeroDangle</RootNamespace>
    <Product>HeroDangle</Product>
    <Version>1.0.0</Version>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.9" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\batman.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\dhirstibomma.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\capsheild.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
